# Site settings
title: Igreja Presbiteriana Pedras Vivas
email: contato@ippedrasvivas.org.br
description: > # this means to ignore newlines until "baseurl:"
 Nossa descrição
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: volnyio
github_username:  volny

# Build settings
markdown: kramdown