# Site settings
title: Associação Reformada de Cultura e Ação Política
email: contato@arcap.org.br
description: > # this means to ignore newlines until "baseurl:"
 Nossa descrição
baseurl: "" # the subpath of your site, e.g. /blog/
url: "arcap" # the base hostname & protocol for your site

twitter_username: 
github_username:  

address:
  - line: Associação Reformada de Cultura e Ação Política
  - line: Rua Gonçalves Dias, 138
  - line: "Recife, Pernambuco, Brasil"
  # Feel free to add more lines here 

# API settings
google_api_key: AIzaSyA8H0jVz_6Hc273rqNYKQ6AAiBvQfVKmYQ

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
